docs:
  docker: docker.onedata.org/onedata-documentation:ID-2a4f7d133a
  output-path: /volumes/docs
gui:
  docker: docker.onedata.org/oz-gui-homepage:VFS-5065-random-anchor-failure
  output-path: /volumes/gui
