docs:
  docker: docker.onedata.org/onedata-documentation:ID-63e43add02
  output-path: /volumes/docs
gui:
  docker: docker.onedata.org/oz-gui-homepage:18.02.0-rc13-static-docs
  output-path: /volumes/gui
