docs:
  docker: docker.onedata.org/onedata-documentation:ID-31bf85714e
  output-path: /volumes/docs
gui:
  docker: docker.onedata.org/oz-gui-homepage:VFS-5065-random-anchor-failure
  output-path: /volumes/gui
