version: '2.0'

services:
  node1.oneprovider:
    image: onedata/oneprovider:18.02.0-rc13
    hostname: node1.oneprovider
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        - "${PWD}/op-worker-overlay.config:/etc/op_worker/overlay.config"
        - "${PWD}/op-panel-overlay.config:/etc/op_panel/overlay.config"
        # data persistence
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        # Server SSL certificates
        #- "${OP_PRIV_KEY_PATH}:/etc/op_panel/certs/web_key.pem"
        #- "${OP_CERT_PATH}:/etc/op_panel/certs/web_cert.pem"
        #- "${OP_CHAIN_PATH}:/etc/op_panel/certs/web_chain.pem"
        # Additional, trusted CA certificates (any filename is accepted)
        #- "${OP_CACERTS_PATH}:/etc/op_panel/cacerts/customCaBundle.pem"
    ports:
      - "80:80"
      - "443:443"
      - "6665:6665"
      - "9443:9443"
    environment:
      # If enabled, a new web cert will be generated with CN matching the
      #   ONEPANEL_GENERATED_CERT_DOMAIN and signed by OnedataTestWebServerCa
      # NOTE: The generation will be performed upon every startup, any
      #   existing certs will be backed up and placed in the same directory.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_GENERATE_TEST_WEB_CERT: "true"  # default: false
      # The generated test web cert will be issued for below domain.
      ONEPANEL_GENERATED_CERT_DOMAIN: "node1.oneprovider"  # default: ""
      # If enabled, onepanel will trust any server that has a cert signed by
      #   the OnedataTestWebServerCa.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_TRUST_TEST_CA: "true"  # default: false



