version: '2.0'

services:
  node1.onezone:
    image: onedata/onezone:19.02.0-beta1
    hostname: node1.onezone
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        # Default configuration override
        - "${PWD}/oz-worker-overlay.config:/etc/oz_worker/overlay.config"
        - "${PWD}/oz-panel-overlay.config:/etc/oz_panel/overlay.config"
        # OpenId configuration
        #- "${AUTH_PATH}:/etc/oz_worker/auth.config"
        # Server SSL certificates
        #- "${OZ_PRIV_KEY_PATH}:/etc/oz_panel/certs/web_key.pem"
        #- "${OZ_CERT_PATH}:/etc/oz_panel/certs/web_cert.pem"
        #- "${OZ_CHAIN_PATH}:/etc/oz_panel/certs/web_chain.pem"
        # Additional, trusted CA certificates (any filename is accepted)
        #- "${OZ_CACERTS_PATH}:/etc/oz_panel/cacerts/customCaBundle.pem"
    networks:
      - scenario2
    environment:
      # If enabled, a new web cert will be generated with CN matching the
      #   ONEPANEL_GENERATED_CERT_DOMAIN and signed by OnedataTestWebServerCa
      # NOTE: The generation will be performed upon every startup, any
      #   existing certs will be backed up and placed in the same directory.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_GENERATE_TEST_WEB_CERT: "true"  # default: false
      # The generated test web cert will be issued for below domain.
      ONEPANEL_GENERATED_CERT_DOMAIN: "node1.onezone"  # default: ""
      # If enabled, onepanel will trust any server that has a cert signed by
      #   the OnedataTestWebServerCa.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_TRUST_TEST_CA: "true"  # default: false

networks:
  scenario2:
